version: "3.8"
services:

  ch-server:
    image: yandex/clickhouse-server:latest
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile: 262144
    volumes:
      - "./.data/clickhouse/data:/var/lib/clickhouse"
      - "./.data/clickhouse/log:/var/log/clickhouse-server"
      - "./.clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./.clickhouse/config/users.xml:/etc/clickhouse-server/users.xml"

  ch-client:
    image: yandex/clickhouse-client:latest
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    depends_on:
      - ch-server
