version: "3.8"
services:

  ch-server:
    image: yandex/clickhouse-server:latest
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile: 262144
    volumes:
      - ./clickhouse/server/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse/server/data:/var/lib/clickhouse/data
      - ./clickhouse/server/initdb.d/yandex_market_category_models.sql:/docker-entrypoint-initdb.d/yandex_market_category_models.sql

  ch-client:
    image: yandex/clickhouse-client:latest
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    depends_on:
      - ch-server
