object Versions {
  lazy val monix                  = "3.4.0"
  lazy val catsCore               = "2.6.1"
  lazy val catsEffect             = "2.5.1"
  lazy val tofu                   = "0.10.1"
  lazy val derevo                 = "0.12.2"
  lazy val supertagged            = "2.0-RC2"
  lazy val enumeratum             = "1.7.0"
  lazy val circe                  = "0.14.1"
  lazy val circeDerivation        = "0.13.0-M5"
  lazy val tethys                 = "0.24.0"
  lazy val vulkan                 = "1.3.0"
  lazy val fs2                    = "3.0.6"
  lazy val fs2Kafka               = "1.7.0"
  lazy val kafkaStreams           = "6.2.0-ce"
  lazy val kafkaStreams4s         = "0.15.0"
  lazy val kafkaStreamsAvroSerde  = "6.2.0"
  lazy val monitoringInterceptors = "6.2.0"
  lazy val http4s                 = "0.21.24"
  lazy val http4sBlazeClient      = "0.21.24"
  lazy val doobie                 = "0.13.4"
  lazy val clickhouseJDBC         = "0.3.1"
  lazy val pureconfig             = "0.14.1"

  lazy val slf4j   = "1.7.31"
  lazy val logback = "1.2.3"

  lazy val betterMonadicFor = "0.3.1"
  lazy val kindProjector    = "0.13.0"

  lazy val scalactic               = "3.2.9"
  lazy val scalatest               = "3.2.9"
  lazy val scalacheck              = "1.15.4"
  lazy val scalatestPlusScalacheck = "3.2.2.0"
}
