object Versions {
  lazy val monix                  = "3.4.0"
  lazy val catsCore               = "2.7.0"
  lazy val catsEffect             = "2.5.4"
  lazy val tofu                   = "0.10.1"
  lazy val derevo                 = "0.12.2"
  lazy val supertagged            = "2.0-RC2"
  lazy val enumeratum             = "1.7.0"
  lazy val circe                  = "0.14.1"
  lazy val circeDerivation        = "0.13.0-M5"
  lazy val tethys                 = "0.25.0"
  lazy val vulkan                 = "1.3.0"
  lazy val fs2                    = "2.5.10"
  lazy val fs2Kafka               = "1.9.0"
  lazy val kafkaStreams           = "7.0.1-ce"
  lazy val kafkaStreams4s         = "0.15.0"
  lazy val kafkaStreamsAvroSerde  = "7.0.1"
  lazy val monitoringInterceptors = "7.0.1"
  lazy val http4s                 = "0.21.31"
  lazy val http4sBlazeClient      = "0.21.31"
  lazy val doobie                 = "0.13.4"
  lazy val clickhouseJDBC         = "0.3.2"
  lazy val pureconfig             = "0.14.1"

  lazy val slf4j   = "1.7.33"
  lazy val logback = "1.2.10"

  lazy val betterMonadicFor = "0.3.1"
  lazy val kindProjector    = "0.13.2"

  lazy val scalactic               = "3.2.10"
  lazy val scalatest               = "3.2.10"
  lazy val scalacheck              = "1.15.4"
  lazy val scalatestPlusScalacheck = "3.2.2.0"
}
