object Versions {
  lazy val monix           = "3.3.0"
  lazy val tofu            = "0.8.0"
  lazy val derevo          = "0.11.5"
  lazy val supertagged     = "2.0-RC2"
  lazy val enumeratum      = "1.6.1"
  lazy val circe           = "0.13.0"
  lazy val circeDerivation = "0.13.0-M4"
  lazy val vulkan          = "1.2.0"
  lazy val fs2             = "2.4.6"
  lazy val fs2Kafka        = "1.1.0+97-b34173aa-SNAPSHOT"
  lazy val http4s          = "0.21.8"
  lazy val asyncHttpClient = "2.12.1"
  lazy val doobie          = "0.9.0"
  lazy val clickhouseJDBC  = "0.2.4"
  lazy val pureconfig      = "0.14.0"
  lazy val logback         = "1.2.3"

  lazy val betterMonadicFor = "0.3.1"
  lazy val kindProjector    = "0.11.0"

  lazy val scalactic               = "3.2.0"
  lazy val scalatest               = "3.2.0"
  lazy val scalacheck              = "1.14.1"
  lazy val scalatestPlusScalacheck = "3.2.2.0"
}
